# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

container: gradle:6.0.1-jdk8

steps:
- script: gradle clean build -Dorg.gradle.daemon=false
  displayName: 'Gradle build'
